### Importing the needed Libraries

In [16]:
import pandas as pd
import numpy as np

In [4]:

#loading the diabetes prediction dataset to a pandas dataframe
diabetes_dataset = pd.read_csv('diabetes_prediction_dataset.csv')

#printing the first 100 rows of dataset
diabetes_dataset.head(5)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0

In [5]:
diabetes_dataset.shape

(100000, 9)

In [6]:
diabetes_dataset.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [102]:
diabetes_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gender               100000 non-null  object
 1   age                  100000 non-null  float64
 2   hypertension         100000 non-null  int64
 3   heart_disease        100000 non-null  int64
 4   smoking_history      100000 non-null  object
 5   bmi                  100000 non-null  float64
 6   HbA1c_level          100000 non-null  float64
 7   blood_glucose_level  100000 non-null  int64
 8   diabetes             100000 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 6.9+ MB

In [7]:
# getting the statisyical measure of thr data
diabetes_dataset.describe()

,age,hypertension,heart_disease,bmi,HbA1c_level,blood_glucose_level,diabetes
count,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,41.885856,0.07485,0.039420,27.320767,5.527507,138.058060,0.085000
std,22.516840,0.26315,0.194593,6.636783,1.070672,40.708136,0.278883
min,0.080000,0.00000,0.000000,10.010000,3.500000,80.000000,0.000000
25%,24.000000,0.00000,0.000000,23.630000,4.800000,100.000000,0.000000
50%,43.000000,0.00000,0.000000,27.320000,5.800000,140.000000,0.000000
75%,60.000000,0.00000,0.000000,29.580000,6.200000,159.000000,0.000000
max,80.000000,1.00000,1.000000,95.690000,9.000000,300.000000,1.000000

In [8]:
diabetes_dataset.describe().T

,count,mean,std,min,25%,50%,75%,max
age,100000.0,41.885856,22.516840,0.08,24.00,43.00,60.00,80.00
hypertension,100000.0,0.074850,0.263150,0.00,0.00,0.00,0.00,1.00
heart_disease,100000.0,0.039420,0.194593,0.00,0.00,0.00,0.00,1.00
bmi,100000.0,27.320767,6.636783,10.01,23.63,27.32,29.58,95.69
HbA1c_level,100000.0,5.527507,1.070672,3.50,4.80,5.80,6.20,9.00
blood_glucose_level,100000.0,138.058060,40.708136,80.00,100.00,140.00,159.00,300.00
diabetes,100000.0,0.085000,0.278883,0.00,0.00,0.00,0.00,1.00

In [9]:
diabetes_dataset.isnull().head(10)

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False

In [98]:
diabetes_dataset.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [10]:
diabetes_dataset.dropna()

,gender,age,hypertension,heart_disease,smoking_history,bmi,HbA1c_level,blood_glucose_level,diabetes
0,Female,80.0,0,1,never,25.19,6.6,140,0
1,Female,54.0,0,0,No Info,27.32,6.6,80,0
2,Male,28.0,0,0,never,27.32,5.7,158,0
3,Female,36.0,0,0,current,23.45,5.0,155,0
4,Male,76.0,1,1,current,20.14,4.8,155,0
...,...,...,...,...,...,...,...,...,...
99995,Female,80.0,0,0,No Info,27.32,6.2,90,0
99996,Female,2.0,0,0,No Info,17.37,6.5,100,0
99997,Male,66.0,0,0,former,27.83,5.7,155,0
99998,Female,24.0,0,0,never,35.42,4.0,100,0
99999,Female,57.0,0,0,current,22.43,6.6,90,0

In [11]:
diabetes_dataset['diabetes'].value_counts()

diabetes
0    91500
1     8500
Name: count, dtype: int64

O-------- means Non Diabetic                                        1-------- Means Diabetic

In [12]:
diabetes_dataset['hypertension'].value_counts()
# if hypentension is 0 that mean non hypten... if 1 it means yes

hypertension
0    92515
1     7485
Name: count, dtype: int64

In [13]:
diabetes_dataset['heart_disease'].value_counts()
# If heart disease is 0 that mean it non whilw 1 means oposite

heart_disease
0    96058
1     3942
Name: count, dtype: int64

In [14]:
diabetes_dataset_copy = diabetes_dataset.copy(deep=True)

In [15]:
diabetes_dataset_copy[['gender', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level']] = diabetes_dataset_copy[['gender', 'hypertension', 'heart_disease', 'smoking_history', 'bmi', 'HbA1c_level', 'blood_glucose_level']].replace(0, np.nan)

NameError: name 'np' is not defined

In [91]:
print(diabetes_dataset_copy.isnull().sum())

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [90]:
p = diabetes_df.hist(figsize=(20, 20))

NameError: name 'diabetes_df' is not defined

In [88]:
mean_values = diabetes_dataset.groupby('diabetes')[numeric_columns].mean()
print(mean_values)

                age  hypertension  heart_disease        bmi  HbA1c_level  \
diabetes
0         40.115187      0.058984       0.029235  26.887163     5.396761
1         60.946588      0.245647       0.149059  31.988382     6.934953

          blood_glucose_level  diabetes
diabetes
0                  132.852470       0.0
1                  194.094706       1.0

In [87]:
# Select numeric columns
numeric_columns = diabetes_dataset.select_dtypes(include=['number']).columns

# Group by 'diabetes' and calculate mean for numeric columns
mean_values = diabetes_dataset.groupby('diabetes')[numeric_columns].mean()
print(mean_values)

                age  hypertension  heart_disease        bmi  HbA1c_level  \
diabetes
0         40.115187      0.058984       0.029235  26.887163     5.396761
1         60.946588      0.245647       0.149059  31.988382     6.934953

          blood_glucose_level  diabetes
diabetes
0                  132.852470       0.0
1                  194.094706       1.0

In [86]:
#seperating the data and labels
X = diabetes_dataset.drop(columns='diabetes', axis=1)
Y = diabetes_dataset['diabetes']

In [85]:
print(X)

       gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19
1      Female  54.0             0              0         No Info  27.32
2        Male  28.0             0              0           never  27.32
3      Female  36.0             0              0         current  23.45
4        Male  76.0             1              1         current  20.14
...       ...   ...           ...            ...             ...    ...
99995  Female  80.0             0              0         No Info  27.32
99996  Female   2.0             0              0         No Info  17.37
99997    Male  66.0             0              0          former  27.83
99998  Female  24.0             0              0           never  35.42
99999  Female  57.0             0              0         current  22.43

       HbA1c_level  blood_glucose_level
0              6.6                  140
1              6.6                   80
2              5.7                  158
3              5.0                  155
4              4.8                  155
...            ...                  ...
99995          6.2                   90
99996          6.5                  100
99997          5.7                  155
99998          4.0                  100
99999          6.6                   90

[100000 rows x 8 columns]

In [84]:
print(Y)

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64

In [83]:
X_numeric = X.select_dtypes(include=['number'])

In [82]:
print("Numeric Data:")

Numeric Data:

In [81]:
print(X_numeric)

        age  hypertension  heart_disease    bmi  HbA1c_level  \
0      80.0             0              1  25.19          6.6
1      54.0             0              0  27.32          6.6
2      28.0             0              0  27.32          5.7
3      36.0             0              0  23.45          5.0
4      76.0             1              1  20.14          4.8
...     ...           ...            ...    ...          ...
99995  80.0             0              0  27.32          6.2
99996   2.0             0              0  17.37          6.5
99997  66.0             0              0  27.83          5.7
99998  24.0             0              0  35.42          4.0
99999  57.0             0              0  22.43          6.6

       blood_glucose_level
0                      140
1                       80
2                      158
3                      155
4                      155
...                    ...
99995                   90
99996                  100
99997                  155
99998                  100
99999                   90

[100000 rows x 6 columns]

In [80]:
# One-Hot Encoding Categorical Variables
X_encoded = pd.get_dummies(X)
print("\nEncoded Data:")
print(X_encoded)

Encoded Data:
        age  hypertension  heart_disease    bmi  HbA1c_level  \
0      80.0             0              1  25.19          6.6
1      54.0             0              0  27.32          6.6
2      28.0             0              0  27.32          5.7
3      36.0             0              0  23.45          5.0
4      76.0             1              1  20.14          4.8
...     ...           ...            ...    ...          ...
99995  80.0             0              0  27.32          6.2
99996   2.0             0              0  17.37          6.5
99997  66.0             0              0  27.83          5.7
99998  24.0             0              0  35.42          4.0
99999  57.0             0              0  22.43          6.6

       blood_glucose_level  gender_Female  gender_Male  gender_Other  \
0                      140           True        False         False
1                       80           True        False         False
2                      158          False         True         False
3                      155           True        False         False
4                      155          False         True         False
...                    ...            ...          ...           ...
99995                   90           True        False         False
99996                  100           True        False         False
99997                  155          False         True         False
99998                  100           True        False         False
99999                   90           True        False         False

       smoking_history_No Info  smoking_history_current  smoking_history_ever  \
0                        False                    False                 False
1                         True                    False                 False
2                        False                    False                 False
3                        False                     True                 False
4                        False                     True                 False
...                        ...                      ...                   ...
99995                     True                    False                 False
99996                     True                    False                 False
99997                    False                    False                 False
99998                    False                    False                 False
99999                    False                     True                 False

       smoking_history_former  smoking_history_never  \
0                       False                   True
1                       False                  False
2                       False                   True
3                       False                  False
4                       False                  False
...                       ...                    ...
99995                   False                  False
99996                   False                  False
99997                    True                  False
99998                   False                   True
99999                   False                  False

       smoking_history_not current
0                            False
1                            False
2                            False
3                            False
4                            False
...                            ...
99995                        False
99996                        False
99997                        False
99998                        False
99999                        False

[100000 rows x 15 columns]

In [79]:
scaler = StandardScaler()

In [78]:
diabetes_dataset_copy = diabetes_dataset.copy(deep=True)
diabetes_dataset_copy[['gender','hypertension', 'heart_disease', 'smoking_history','bmi', 'HbA1c_level', 'blood_glucose_level']] = diabetes_dataset_copy[['gender','hypertension', 'heart_disease', 'smoking_history','bmi', 'HbA1c_level', 'blood_glucose_level']].replace(0, np.NaN)

# Showing the count of NaNs
print(diabetes_dataset_copy.isnull().sum())

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

In [76]:
scaler.fit(X_numeric)

StandardScaler()